# This workflow will install PyCoSa including dependencies and run pytest
name: CI

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        pytest-specifier: [
          '-m "not long"',
          'tests/test_examples.py::test_suzuki_example',
          ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install dependencies
      run: |
        uv pip install --system pytest
        uv pip install --system -e .
    - name: Test with pytest
      run: |
        pytest -v -s ${{matrix.pytest-specifier}}
